name: Proxy Scraper - Cleanest Approach

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      proxy_types:
        description: 'Proxy types: socks5,socks4,http or "all"'
        required: true
        default: 'all'
        type: string

jobs:
  scrape-proxies:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      timeout-minutes: 5

    - name: Set proxy types
      id: types
      run: |
        INPUT="${{ github.event.inputs.proxy_types || 'all' }}"
        if [ "$INPUT" = "all" ]; then
          echo "types=socks5 socks4 http" >> $GITHUB_OUTPUT
        else
          echo "types=$(echo $INPUT | tr ',' ' ')" >> $GITHUB_OUTPUT
        fi

    - name: Run proxy scraper for each type
      run: |
        for type in ${{ steps.types.outputs.types }}; do
          echo "Processing $type proxies..."
          timeout 1800 python proxy_scraper.py --proxy-type "$type" || echo "Timeout for $type"
          if [ -f proxylist.jdproxies ]; then
            cp proxylist.jdproxies "proxylist-$type.jdproxies"
            echo "Saved proxylist-$type.jdproxies"
          fi
          sleep 10
        done

    - name: Create combine script using individual echo statements
      run: |
        echo "import json" > c.py
        echo "import glob" >> c.py
        echo "p=[]" >> c.py
        echo "for f in glob.glob('proxylist-*.jdproxies'):" >> c.py
        echo " with open(f) as x:" >> c.py
        echo "  p.extend(json.load(x).get('customProxyList',[]))" >> c.py
        echo "s=set()" >> c.py
        echo "u=[]" >> c.py
        echo "for x in p:" >> c.py
        echo " try:" >> c.py
        echo "  k=x['proxy']['address']+':'+str(x['proxy']['port'])" >> c.py
        echo "  if k not in s:" >> c.py
        echo "   s.add(k)" >> c.py
        echo "   u.append(x)" >> c.py
        echo " except:pass" >> c.py
        echo "u.sort(key=lambda x:x.get('response_time',999))" >> c.py
        echo "json.dump({'customProxyList':u},open('proxylist.jdproxies','w'),indent=2)" >> c.py
        echo "print(f'Combined {len(u)} proxies')" >> c.py

    - name: Run combine script
      run: python c.py && rm c.py

    - name: Verify files
      run: |
        echo "Generated files:"
        ls -la proxylist*.jdproxies
        if [ -f proxylist.jdproxies ]; then
          echo "Combined file size: $(wc -c < proxylist.jdproxies) bytes"
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: proxy-lists-${{ github.run_number }}
        path: proxylist*.jdproxies
        retention-days: 7

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin ${{ github.ref_name }}
        git add proxylist*.jdproxies
        if ! git diff --cached --quiet; then
          git commit -m "Update proxy lists - $(date '+%Y-%m-%d %H:%M UTC')"
          git push origin ${{ github.ref_name }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
