name: Proxy Scraper - Fast Matrix

on:
  schedule:
    # Run every 6 hours (at 00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  scrape-single-types:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false  # Continue other jobs even if one fails
      matrix:
        proxy_type: [socks5, socks4, http]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      timeout-minutes: 5

    - name: Run proxy scraper for ${{ matrix.proxy_type }}
      run: |
        timeout 1500 python proxy_scraper.py --proxy-type ${{ matrix.proxy_type }} || echo "⚠️  Validation timed out after 25 minutes for ${{ matrix.proxy_type }}"
      timeout-minutes: 28

    - name: Check results for ${{ matrix.proxy_type }}
      run: |
        if [ -f proxylist.jdproxies ]; then
          echo "✅ ${{ matrix.proxy_type }} proxy file generated"
          echo "📊 File size: $(wc -c < proxylist.jdproxies) bytes"
          # Rename to include proxy type
          mv proxylist.jdproxies proxylist-${{ matrix.proxy_type }}.jdproxies
        else
          echo "⚠️  No proxy file generated for ${{ matrix.proxy_type }}"
        fi

    - name: Upload ${{ matrix.proxy_type }} proxy list
      if: hashFiles('proxylist-${{ matrix.proxy_type }}.jdproxies') != ''
      uses: actions/upload-artifact@v4
      with:
        name: proxy-list-${{ matrix.proxy_type }}-${{ github.run_number }}
        path: proxylist-${{ matrix.proxy_type }}.jdproxies
        retention-days: 7

    - name: Commit ${{ matrix.proxy_type }} proxy list
      if: hashFiles('proxylist-${{ matrix.proxy_type }}.jdproxies') != ''
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add proxylist-${{ matrix.proxy_type }}.jdproxies

        if git diff --cached --quiet; then
          echo "No changes to commit for ${{ matrix.proxy_type }}"
        else
          git commit -m "Update ${{ matrix.proxy_type }} proxy list - $(date '+%Y-%m-%d %H:%M UTC')"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      timeout-minutes: 2
